server:
  port: 9088
#logging:
#  config: classpath:log4j2.xml

#debug: true

# DataSource Config
#spring:
#  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:h2:mem:rest-service
#    username: root
#    password: root
#  sql:
#    init:
#      schema-locations: classpath:db/schema-h2.sql
#      data-locations: classpath:db/data-h2.sql
#      mode: always
#  # 启用 h2 console
#  h2:
#    console:
#      enabled: true
#      path: /h2-console  # 访问路径
#      settings:
#        trace: false
#        web-allow-others: false


# application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bench_mark
    username: geeker
    password: geeker
    driver-class-name: com.mysql.cj.jdbc.Driver




# 基于配置生效对应Bean
notification:
  type: sms

#
#spring:
#  aop:
#    proxy-target-class: false